/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import static vista.Estilos.BORDE_GRIS;
import static vista.Estilos.BORDE_ROJO;
import static vista.Estilos.FG_COLOR;
import static vista.Estilos.FUENTE_LBL;
import static vista.Estilos.FUENTE_TITULOS;
import static vista.Estilos.FUENTE_TXT;
import static vista.Estilos.GRIS_BG;
import static vista.Estilos.ROJO;
import static vista.Estilos.ROJO_OBS;

/**
 *
 * @author Dell
 */
public class PnSucursal extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PnSucursal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnModificaciones = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        txtInfo1 = new javax.swing.JTextField();
        lblNumSucursal1 = new javax.swing.JLabel();
        txtNumSucursal1 = new javax.swing.JTextField();
        lblUbicacion1 = new javax.swing.JLabel();
        txtUbicacion1 = new javax.swing.JTextField();
        lblEmpleados1 = new javax.swing.JLabel();
        tbdpnEmpleados1 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblGerentes1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCajeros1 = new javax.swing.JTable();
        lblSalas1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSalas1 = new javax.swing.JTable();
        btnGuardar1 = new javax.swing.JButton();
        lblIcono1 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pnConsultas = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        lblNumSucursal2 = new javax.swing.JLabel();
        txtNumSucursal2 = new javax.swing.JTextField();
        txtInfo2 = new javax.swing.JTextField();
        lblUbicacion2 = new javax.swing.JLabel();
        txtUbicacion2 = new javax.swing.JTextField();
        lblEmpleados2 = new javax.swing.JLabel();
        tbdpnEmpleados2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCajeros2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGerentes2 = new javax.swing.JTable();
        lblSalas2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSalas2 = new javax.swing.JTable();
        btnBuscar2 = new javax.swing.JButton();
        lblIcono2 = new javax.swing.JLabel();
        pnRegistro = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        lblNumSucursal3 = new javax.swing.JLabel();
        txtNumSucursal3 = new javax.swing.JTextField();
        lblUbicacion3 = new javax.swing.JLabel();
        txtUbicacion3 = new javax.swing.JTextField();
        lblNumSalas = new javax.swing.JLabel();
        btnRegSalas = new javax.swing.JButton();
        txtNumSalas = new javax.swing.JTextField();
        lblNumEmps = new javax.swing.JLabel();
        txtNumEmps = new javax.swing.JTextField();
        btnRegEmps = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnGuardar2 = new javax.swing.JButton();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(FG_COLOR);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(FUENTE_LBL);
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        pnModificaciones.setBackground(GRIS_BG);

        lblTitulo1.setFont(FUENTE_TITULOS);
        lblTitulo1.setForeground(FG_COLOR);
        lblTitulo1.setText("Sucursales");

        txtInfo1.setEditable(false);
        txtInfo1.setBackground(new java.awt.Color(255, 255, 255));
        txtInfo1.setFont(FUENTE_LBL);
        txtInfo1.setText("Ingrese el número de sucursal para hacer la modificación de la misma");

        lblNumSucursal1.setFont(FUENTE_LBL);
        lblNumSucursal1.setForeground(FG_COLOR);
        lblNumSucursal1.setText("Número de sucursal:");

        txtNumSucursal1.setBackground(GRIS_BG);
        txtNumSucursal1.setFont(FUENTE_TXT);
        txtNumSucursal1.setForeground(FG_COLOR);
        txtNumSucursal1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumSucursal1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumSucursal1FocusLost(evt);
            }
        });

        lblUbicacion1.setFont(FUENTE_LBL);
        lblUbicacion1.setForeground(FG_COLOR);
        lblUbicacion1.setText("Ubicación:");

        txtUbicacion1.setBackground(GRIS_BG);
        txtUbicacion1.setFont(FUENTE_TXT);
        txtUbicacion1.setForeground(FG_COLOR);
        txtUbicacion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUbicacion1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUbicacion1FocusLost(evt);
            }
        });
        txtUbicacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicacion1ActionPerformed(evt);
            }
        });

        lblEmpleados1.setFont(FUENTE_LBL);
        lblEmpleados1.setForeground(FG_COLOR);
        lblEmpleados1.setText("Empleados:");

        tbdpnEmpleados1.setForeground(FG_COLOR);
        tbdpnEmpleados1.setFont(FUENTE_LBL);

        tblGerentes1.setBackground(GRIS_BG);
        tblGerentes1.setFont(FUENTE_LBL);
        tblGerentes1.setForeground(FG_COLOR);
        tblGerentes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Número de teléfono", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblGerentes1);

        tbdpnEmpleados1.addTab("Gerentes", jScrollPane5);

        tblCajeros1.setBackground(GRIS_BG);
        tblCajeros1.setFont(FUENTE_LBL);
        tblCajeros1.setForeground(FG_COLOR);
        tblCajeros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Número de Teléfono", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblCajeros1);

        tbdpnEmpleados1.addTab("Cajeros", jScrollPane4);

        lblSalas1.setFont(FUENTE_LBL);
        lblSalas1.setForeground(FG_COLOR);
        lblSalas1.setText("Salas:");

        tblSalas1.setBackground(GRIS_BG);
        tblSalas1.setFont(FUENTE_LBL);
        tblSalas1.setForeground(FG_COLOR);
        tblSalas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. de sala", "No. de asientos", "No. de filas", "No. de columnas", "Costo de boleto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblSalas1);

        btnGuardar1.setBackground(ROJO);
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gicon.png"))); // NOI18N
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        lblIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pnicono.png"))); // NOI18N

        btnBuscar1.setBackground(ROJO);
        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sicon.png"))); // NOI18N

        javax.swing.GroupLayout pnModificacionesLayout = new javax.swing.GroupLayout(pnModificaciones);
        pnModificaciones.setLayout(pnModificacionesLayout);
        pnModificacionesLayout.setHorizontalGroup(
            pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModificacionesLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addGroup(pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModificacionesLayout.createSequentialGroup()
                        .addComponent(lblTitulo1)
                        .addGap(304, 304, 304))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModificacionesLayout.createSequentialGroup()
                        .addComponent(txtInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModificacionesLayout.createSequentialGroup()
                        .addGroup(pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnModificacionesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblSalas1))
                            .addGroup(pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbdpnEmpleados1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
            .addGroup(pnModificacionesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnModificacionesLayout.createSequentialGroup()
                        .addGroup(pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumSucursal1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUbicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUbicacion1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar1)
                        .addGap(71, 71, 71))
                    .addGroup(pnModificacionesLayout.createSequentialGroup()
                        .addGroup(pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumSucursal1)
                            .addComponent(lblEmpleados1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnModificacionesLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(btnGuardar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModificacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIcono1)
                .addGap(251, 251, 251))
        );
        pnModificacionesLayout.setVerticalGroup(
            pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnModificacionesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumSucursal1)
                .addGroup(pnModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnModificacionesLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtNumSucursal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUbicacion1)
                        .addGap(10, 10, 10)
                        .addComponent(txtUbicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnModificacionesLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnBuscar1)))
                .addGap(18, 18, 18)
                .addComponent(lblEmpleados1)
                .addGap(6, 6, 6)
                .addComponent(tbdpnEmpleados1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSalas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar1)
                .addGap(18, 18, 18)
                .addComponent(lblIcono1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificaciones", pnModificaciones);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminaciones", jPanel4);

        pnConsultas.setBackground(GRIS_BG);

        lblTitulo2.setFont(FUENTE_TITULOS);
        lblTitulo2.setForeground(FG_COLOR);
        lblTitulo2.setText("Sucursales");

        lblNumSucursal2.setFont(FUENTE_LBL);
        lblNumSucursal2.setForeground(FG_COLOR);
        lblNumSucursal2.setText("Número de sucursal:");

        txtNumSucursal2.setBackground(GRIS_BG);
        txtNumSucursal2.setFont(FUENTE_TXT);
        txtNumSucursal2.setForeground(FG_COLOR);
        txtNumSucursal2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumSucursal2FocusGained(evt);
            }
        });

        txtInfo2.setEditable(false);
        txtInfo2.setBackground(new java.awt.Color(255, 255, 255));
        txtInfo2.setFont(FUENTE_LBL);
        txtInfo2.setText("Ingrese el número de sucursal o su ubicación para realizar la búsqueda");
        txtInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInfo2ActionPerformed(evt);
            }
        });

        lblUbicacion2.setFont(FUENTE_LBL);
        lblUbicacion2.setForeground(FG_COLOR);
        lblUbicacion2.setText("Ubicación:");

        txtUbicacion2.setBackground(GRIS_BG);
        txtUbicacion2.setFont(FUENTE_TXT);
        txtUbicacion2.setForeground(FG_COLOR);

        lblEmpleados2.setFont(FUENTE_LBL);
        lblEmpleados2.setForeground(FG_COLOR);
        lblEmpleados2.setText("Empleados:");

        tbdpnEmpleados2.setForeground(FG_COLOR);
        tbdpnEmpleados2.setToolTipText("");
        tbdpnEmpleados2.setFont(FUENTE_LBL);

        tblCajeros2.setBackground(GRIS_BG);
        tblCajeros2.setFont(FUENTE_LBL);
        tblCajeros2.setForeground(FG_COLOR);
        tblCajeros2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Número de Teléfono", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCajeros2);

        tbdpnEmpleados2.addTab("Cajeros", jScrollPane2);

        tblGerentes2.setBackground(GRIS_BG);
        tblGerentes2.setFont(FUENTE_LBL);
        tblGerentes2.setForeground(FG_COLOR);
        tblGerentes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Número de Teléfono", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGerentes2);

        tbdpnEmpleados2.addTab("Gerentes", jScrollPane1);

        lblSalas2.setFont(FUENTE_LBL);
        lblSalas2.setForeground(FG_COLOR);
        lblSalas2.setText("Salas:");

        tblSalas2.setBackground(GRIS_BG);
        tblSalas2.setFont(FUENTE_LBL);
        tblSalas2.setForeground(FG_COLOR);
        tblSalas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. de sala", "No. de asientos", "No. de filas", "No. de columnas", "Costo de boleto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSalas2);

        btnBuscar2.setBackground(ROJO);
        btnBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sicon.png"))); // NOI18N

        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pnicono.png"))); // NOI18N

        javax.swing.GroupLayout pnConsultasLayout = new javax.swing.GroupLayout(pnConsultas);
        pnConsultas.setLayout(pnConsultasLayout);
        pnConsultasLayout.setHorizontalGroup(
            pnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConsultasLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(lblIcono2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnConsultasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalas2)
                    .addComponent(lblNumSucursal2)
                    .addComponent(lblEmpleados2)
                    .addGroup(pnConsultasLayout.createSequentialGroup()
                        .addGroup(pnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumSucursal2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUbicacion2)
                            .addComponent(txtUbicacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnBuscar2)
                        .addGap(74, 74, 74))))
            .addGroup(pnConsultasLayout.createSequentialGroup()
                .addGroup(pnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnConsultasLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(tbdpnEmpleados2, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)))
                    .addGroup(pnConsultasLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(lblTitulo2))
                    .addGroup(pnConsultasLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(txtInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnConsultasLayout.setVerticalGroup(
            pnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConsultasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblNumSucursal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnConsultasLayout.createSequentialGroup()
                        .addComponent(txtNumSucursal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUbicacion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUbicacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnConsultasLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnBuscar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmpleados2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbdpnEmpleados2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblIcono2)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultas", pnConsultas);

        pnRegistro.setBackground(GRIS_BG);
        pnRegistro.setForeground(FG_COLOR);

        lblTitulo3.setFont(FUENTE_TITULOS);
        lblTitulo3.setForeground(FG_COLOR);
        lblTitulo3.setText("Sucursales");

        lblNumSucursal3.setFont(FUENTE_LBL);
        lblNumSucursal3.setForeground(FG_COLOR);
        lblNumSucursal3.setText("Número de Sucursal:");

        txtNumSucursal3.setBackground(GRIS_BG);
        txtNumSucursal3.setFont(FUENTE_TXT);
        txtNumSucursal3.setForeground(FG_COLOR);

        lblUbicacion3.setFont(FUENTE_LBL);
        lblUbicacion3.setForeground(FG_COLOR);
        lblUbicacion3.setText("Ubicación:");

        txtUbicacion3.setBackground(GRIS_BG);
        txtUbicacion3.setFont(FUENTE_TXT);
        txtUbicacion3.setForeground(FG_COLOR);

        lblNumSalas.setFont(FUENTE_LBL);
        lblNumSalas.setForeground(FG_COLOR);
        lblNumSalas.setText("Número de salas:");

        btnRegSalas.setBackground(ROJO);
        btnRegSalas.setFont(FUENTE_LBL);
        btnRegSalas.setForeground(FG_COLOR);
        btnRegSalas.setText("Registro de salas");
        btnRegSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegSalasActionPerformed(evt);
            }
        });

        txtNumSalas.setBackground(GRIS_BG);
        txtNumSalas.setFont(FUENTE_TXT);
        txtNumSalas.setForeground(FG_COLOR);

        lblNumEmps.setFont(FUENTE_LBL);
        lblNumEmps.setForeground(FG_COLOR);
        lblNumEmps.setText("Número de empleados:");

        txtNumEmps.setBackground(GRIS_BG);
        txtNumEmps.setFont(FUENTE_TXT);
        txtNumEmps.setForeground(FG_COLOR);

        btnRegEmps.setBackground(ROJO);
        btnRegEmps.setFont(FUENTE_LBL);
        btnRegEmps.setForeground(FG_COLOR);
        btnRegEmps.setText("Registro de empleados");
        btnRegEmps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegEmpsActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pnicono.png"))); // NOI18N

        btnGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gicon.png"))); // NOI18N

        javax.swing.GroupLayout pnRegistroLayout = new javax.swing.GroupLayout(pnRegistro);
        pnRegistro.setLayout(pnRegistroLayout);
        pnRegistroLayout.setHorizontalGroup(
            pnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroLayout.createSequentialGroup()
                .addGroup(pnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumSucursal3)
                            .addComponent(lblUbicacion3)
                            .addComponent(txtNumSucursal3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUbicacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnRegistroLayout.createSequentialGroup()
                                    .addComponent(lblNumEmps)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNumEmps, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRegEmps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnRegistroLayout.createSequentialGroup()
                                    .addComponent(lblNumSalas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNumSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnRegSalas)))))
                    .addGroup(pnRegistroLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel9))
                    .addGroup(pnRegistroLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblTitulo3))
                    .addGroup(pnRegistroLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(btnGuardar2))
                    .addGroup(pnRegistroLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel11)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        pnRegistroLayout.setVerticalGroup(
            pnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRegistroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo3)
                .addGap(28, 28, 28)
                .addComponent(lblNumSucursal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumSucursal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUbicacion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUbicacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSalas)
                    .addComponent(btnRegSalas)
                    .addComponent(txtNumSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumEmps)
                    .addComponent(txtNumEmps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegEmps))
                .addGap(56, 56, 56)
                .addComponent(btnGuardar2)
                .addGap(104, 104, 104)
                .addComponent(jLabel11)
                .addGap(276, 276, 276)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro", pnRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegSalasActionPerformed

    private void btnRegEmpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegEmpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegEmpsActionPerformed

    private void txtUbicacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacion1ActionPerformed

    private void txtInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfo2ActionPerformed

    private void txtNumSucursal1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumSucursal1FocusGained
        // TODO add your handling code here:
        txtNumSucursal1.setBorder(BORDE_ROJO);
    }//GEN-LAST:event_txtNumSucursal1FocusGained

    private void txtNumSucursal1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumSucursal1FocusLost
        // TODO add your handling code here:
        txtNumSucursal1.setBorder(BORDE_GRIS);
    }//GEN-LAST:event_txtNumSucursal1FocusLost

    private void txtUbicacion1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbicacion1FocusGained
        // TODO add your handling code here:
        txtUbicacion1.setBorder(BORDE_ROJO);
    }//GEN-LAST:event_txtUbicacion1FocusGained

    private void txtUbicacion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbicacion1FocusLost
        // TODO add your handling code here:
        txtUbicacion1.setBorder(BORDE_GRIS);
    }//GEN-LAST:event_txtUbicacion1FocusLost

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void txtNumSucursal2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumSucursal2FocusGained
        // TODO add your handling code here:
        txtNumSucursal2.setBorder(BORDE_ROJO);
    }//GEN-LAST:event_txtNumSucursal2FocusGained

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed
    
    private void txtNumSucursal2FocusLost(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
        txtNumSucursal2.setBorder(BORDE_GRIS);
    }          
    
    private void txtUbicacion2FocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
        txtUbicacion2.setBorder(BORDE_ROJO);
    }                                           
    
    private void txtUbicacion2FocusLost(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
        txtUbicacion2.setBorder(BORDE_GRIS);
    }    
    
    private void txtNumSucursal3FocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
        txtNumSucursal3.setBorder(BORDE_ROJO);
    }                                           
    
    private void txtNumSucursal3FocusLost(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
        txtNumSucursal3.setBorder(BORDE_GRIS);
    }   
    
    private void txtUbicacion3FocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
        txtUbicacion3.setBorder(BORDE_ROJO);
    }                                           
    
    private void txtUbicacion3FocusLost(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
        txtUbicacion3.setBorder(BORDE_GRIS);
    }
    
    private void btnBuscar1MouseEntered(java.awt.event.MouseEvent evt) {                                         
        btnBuscar1.setBackground(ROJO_OBS);
    }                                        

    private void btnBuscar1MouseExited(java.awt.event.MouseEvent evt) {                                        
        btnBuscar1.setBackground(ROJO);
    } 
    
    private void btnBuscar2MouseEntered(java.awt.event.MouseEvent evt) {                                         
        btnBuscar2.setBackground(ROJO_OBS);
    }                                        

    private void btnBuscar2MouseExited(java.awt.event.MouseEvent evt) {                                        
        btnBuscar2.setBackground(ROJO);
    }
    
    private void btnGuardar1MouseEntered(java.awt.event.MouseEvent evt) {                                         
        btnGuardar1.setBackground(ROJO_OBS);
    }                                        

    private void btnGuardar11MouseExited(java.awt.event.MouseEvent evt) {                                        
        btnGuardar1.setBackground(ROJO);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnRegEmps;
    private javax.swing.JButton btnRegSalas;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEmpleados1;
    private javax.swing.JLabel lblEmpleados2;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblNumEmps;
    private javax.swing.JLabel lblNumSalas;
    private javax.swing.JLabel lblNumSucursal1;
    private javax.swing.JLabel lblNumSucursal2;
    private javax.swing.JLabel lblNumSucursal3;
    private javax.swing.JLabel lblSalas1;
    private javax.swing.JLabel lblSalas2;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblUbicacion1;
    private javax.swing.JLabel lblUbicacion2;
    private javax.swing.JLabel lblUbicacion3;
    private javax.swing.JPanel pnConsultas;
    private javax.swing.JPanel pnModificaciones;
    private javax.swing.JPanel pnRegistro;
    private javax.swing.JTabbedPane tbdpnEmpleados1;
    private javax.swing.JTabbedPane tbdpnEmpleados2;
    private javax.swing.JTable tblCajeros1;
    private javax.swing.JTable tblCajeros2;
    private javax.swing.JTable tblGerentes1;
    private javax.swing.JTable tblGerentes2;
    private javax.swing.JTable tblSalas1;
    private javax.swing.JTable tblSalas2;
    private javax.swing.JTextField txtInfo1;
    private javax.swing.JTextField txtInfo2;
    private javax.swing.JTextField txtNumEmps;
    private javax.swing.JTextField txtNumSalas;
    private javax.swing.JTextField txtNumSucursal1;
    private javax.swing.JTextField txtNumSucursal2;
    private javax.swing.JTextField txtNumSucursal3;
    private javax.swing.JTextField txtUbicacion1;
    private javax.swing.JTextField txtUbicacion2;
    private javax.swing.JTextField txtUbicacion3;
    // End of variables declaration//GEN-END:variables


}

